build:
    image: rust:$$RUST_VERSION
    commands:
        # a bit of hackery is required for a pseudo-TTY to be
        # available to `rpassword` during the test
        - "script --return -c 'cargo test' /dev/null"

matrix:
    RUST_VERSION:
        - '1.8'
        - '1.9'
        - '1.10'
        - 'stable'
