[package]

name = "rpassword"
version = "0.0.4"
authors = ["Conrad Kleinespel <conradk@conradk.com>"]
description = "Read passwords in console applications."
license = "Apache-2.0"
homepage = "https://github.com/conradkleinespel/rustastic-password"
readme = "README.md"
keywords = ["read", "password"]

[dependencies.termios]
# waiting for an update of termios to add this
path = "../tios"

[dependencies]
libc = "0.1.5"
